feat: initial RPC commands
Added two RPC commands:
- `estimate-gas-publish-module`
- `gas-to-weight`

Examples:

Valid case (the value is hardcoded on the server side to 123123):
```
smove node rpc gas-to-weight --gas 32
Value of 325 gas converted to weight has a value of Weight (ref_time: 1123123, proof_size: 0)
```

Valid case:
```
smove node rpc estimate-gas-publish-module --account-id 12bzRJfh7arnnfPPUZHeJUaE62QLEwhK48QnH9LXeK2m1iZU --module-path Vector.mv
Estimated gas: Estimate (gas_used: 18446744073709519115, vm_status_code: EXECUTED)
```

Invalid case (invalid SS58 address):
```
smove node rpc estimate-gas-publish-module --account-id 12bzRJfh7arnnfPPUZHeJUaE62QLEwhK48QnH9LXeK2m1iZs --module-path Vector.mv
Error: RPC result failure

Caused by:
    0: ErrorObject { code: InvalidParams, message: "Invalid checksum", data: None }
    1: ErrorObject { code: InvalidParams, message: "Invalid checksum", data: None }
```

Invalid case (a module cannot be published without the dependent module):
```
smove node rpc estimate-gas-publish-module --account-id 12bzRJfh7arnnfPPUZHeJUaE62QLEwhK48QnH9LXeK2m1iZU --module-path DependsOnVector.mv
Estimated gas: Estimate (gas_used: 0, vm_status_code: LINKER_ERROR)
```

Invalid case (file doesn't exist):
```
smove node rpc estimate-gas-publish-module --account-id 12bzRJfh7arnnfPPUZHeJUaE62QLEwhK48QnH9LXeK2m1iZU --module-path gadshg
Error: Failure to read filename gadshg

Caused by:
  No such file or directory (os error 2)
```